### ISSUE TITLE
login doesn't work with django-cacheops 2.2

### ISSUE THREAD

**Issue by harvestli** [Suor/django-cacheops#118]
Django 1.6.5 with django-cacheops 2.2, single tread mode, get exception when login

if downgrade django-cacheops to 2.1.1, no issue.

following are the exception and traceback

> Request Method: POST
> Request URL:    http://127.0.0.1:8000/admin/
> Django Version: 1.6.5
> Exception Type: AttributeError
> Exception Value:  
> 'thread._local' object has no attribute 'depth'

```
Environment:


Request Method: POST
Request URL: http://127.0.0.1:8000/admin/

Django Version: 1.6.5
Python Version: 2.7.5
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'django.contrib.sites',
 'cacheops',
 'south',
 'app',
 'debug_toolbar')
Installed Middleware:
('debug_toolbar.middleware.DebugToolbarMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware')


Traceback:
File "/Users/lli/work/eduhack_server/venv/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  112.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/Users/lli/work/eduhack_server/venv/lib/python2.7/site-packages/django/contrib/admin/sites.py" in wrapper
  215.                 return self.admin_view(view, cacheable)(*args, **kwargs)
File "/Users/lli/work/eduhack_server/venv/lib/python2.7/site-packages/django/utils/decorators.py" in _wrapped_view
  99.                     response = view_func(request, *args, **kwargs)
File "/Users/lli/work/eduhack_server/venv/lib/python2.7/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
  52.         response = view_func(request, *args, **kwargs)
File "/Users/lli/work/eduhack_server/venv/lib/python2.7/site-packages/django/contrib/admin/sites.py" in inner
  197.                 return self.login(request)
File "/Users/lli/work/eduhack_server/venv/lib/python2.7/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
  52.         response = view_func(request, *args, **kwargs)
File "/Users/lli/work/eduhack_server/venv/lib/python2.7/site-packages/django/contrib/admin/sites.py" in login
  330.         return login(request, **defaults)
File "/Users/lli/work/eduhack_server/venv/lib/python2.7/site-packages/django/views/decorators/debug.py" in sensitive_post_parameters_wrapper
  75.             return view(request, *args, **kwargs)
File "/Users/lli/work/eduhack_server/venv/lib/python2.7/site-packages/django/utils/decorators.py" in _wrapped_view
  99.                     response = view_func(request, *args, **kwargs)
File "/Users/lli/work/eduhack_server/venv/lib/python2.7/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
  52.         response = view_func(request, *args, **kwargs)
File "/Users/lli/work/eduhack_server/venv/lib/python2.7/site-packages/django/contrib/auth/views.py" in login
  43.             auth_login(request, form.get_user())
File "/Users/lli/work/eduhack_server/venv/lib/python2.7/site-packages/django/contrib/auth/__init__.py" in login
  89.     user_logged_in.send(sender=user.__class__, request=request, user=user)
File "/Users/lli/work/eduhack_server/venv/lib/python2.7/site-packages/django/dispatch/dispatcher.py" in send
  185.             response = receiver(signal=self, sender=sender, **named)
File "/Users/lli/work/eduhack_server/venv/lib/python2.7/site-packages/django/contrib/auth/models.py" in update_last_login
  30.     user.save(update_fields=['last_login'])
File "/Users/lli/work/eduhack_server/venv/lib/python2.7/site-packages/django/db/models/base.py" in save
  545.                        force_update=force_update, update_fields=update_fields)
File "/Users/lli/work/eduhack_server/venv/lib/python2.7/site-packages/django/db/models/base.py" in save_base
  582.                                    update_fields=update_fields, raw=raw, using=using)
File "/Users/lli/work/eduhack_server/venv/lib/python2.7/site-packages/django/dispatch/dispatcher.py" in send
  185.             response = receiver(signal=self, sender=sender, **named)
File "/Users/lli/work/eduhack_server/venv/lib/python2.7/site-packages/cacheops/query.py" in _post_save
  350.             invalidate_obj(old)
File "/Users/lli/work/eduhack_server/venv/lib/python2.7/site-packages/cacheops/invalidation.py" in invalidate_obj
  33.     invalidate_dict(model, get_obj_dict(model, obj))
File "/Users/lli/work/eduhack_server/venv/lib/python2.7/site-packages/cacheops/invalidation.py" in invalidate_dict
  20.     if _no_invalidation_mode.depth:

Exception Type: AttributeError at /admin/
Exception Value: 'thread._local' object has no attribute 'depth'
```
