### ISSUE TITLE
Error with Django 1.6

### ISSUE THREAD

**Issue by foobarbecue** [Suor/django-cacheops#48]
Hi, I imagine cacheops is not supposed to work with the as-yet-unreleased Django 1.6, but I thought I'd let you know what happens when I try. I get:

AttributeError at /flight/2013-07-15-05-25-1log_2/

'WhereNode' object has no attribute 'subtree_parents'

Request Method:     GET
Request URL:    http://afterflight.foobarbecue.com:8002/flight/2013-07-15-05-25-1log_2/
Django Version:     1.6b4
Exception Type:     AttributeError
Exception Value:    

'WhereNode' object has no attribute 'subtree_parents'
