### ISSUE TITLE
Django Cacheops incompatible with Django 4.2 - Query.add_annotation() got an unexpected keyword argument 'is_summary'

### ISSUE THREAD

**Issue by gorillamania** [Suor/django-cacheops#450]
loan_amount = self.loan_set.filter(status=Loan.ACTIVE).aggregate(models.Sum("amount"))["amount__sum"] or 0

This worked with Django 4.17

**Comment by gorillamania** [comment]
Looks like this was fixed in version 7.0
