### ISSUE TITLE
invalidated_update() not working on Django 1.8

### ISSUE THREAD

**Issue by jbharrell92** [Suor/django-cacheops#193]
It's extremely likely that I'm just doing something silly, but I tried to implement `invalidated_update` today and got the following error:

`'QuerySet' object has no attribute 'invalidated_update'`

here's my code:

```
notifications = Notification.objects.filter(
    message__thread=thread,
    user=request.user,
    read=False
)
unread = notifications.invalidated_update(read=True) > 0
```

**Comment by Suor** [comment]
`.invalidated_update()` is only available in master branch and not in any published version.

The situation is a bit confusing because cacheops doesn't have docs separate from README, which always refers to latest unstable version (master branch).
